/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(message_GridCell, message_GridCell, AUTO)


PB_BIND(message_Pose, message_Pose, AUTO)


PB_BIND(message_ServerCommand, message_ServerCommand, AUTO)


PB_BIND(message_RomiData, message_RomiData, AUTO)




